services:
  - type: web
    name: shl-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: PORT
        value: 10000
